export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  presets: [
    require('@rise8/tailwind-pixel-perfect-preset')
  ],
  theme: {
    extend: {
      colors: {
        "cornflower-blue": "#6175de",
        "iris": "#495dc6",
        "white": "#ffffff",
        "dark": "#202935",
        "cloudy-blue": "#cfd6de",
        "dark-two": "#212934",
        "denim-blue": "#3547a4",
        "dark-slate-blue": "#1e2c6d",
        "pale-grey": "#f8f9fa",
        "pale-grey-two": "#e1e7eb",
        "blush": "#f27979",
        "wheat": "#fcd97e",
        "dull-teal": "#53a691",
        "dark-three": "#1e2936",
        "bluey-grey": "#8695a9",
        "bluey-grey-two": "#8095ad",
        "iris-10": "#495dc6",
        "iris-30": "#495dc6",
        "dark-blue-grey": "#15293a",
        "bluey-grey-three": "#8895a7",
        "bluey-grey-four": "#8395ab",
        "white-two": "#f2f2f2",
        "white-three": "#e6e6e6",
        "cloudy-blue-two": "#b8c4ce",
        "pale-gold": "#fdd368",
        "pale-gold-30": "#fdd368",
        "light-mustard": "#f4ca64",
        "light-mustard-10": "#f4ca64",
        "dark-four": "#1c2937",
        "dark-five": "#1b2937",
        "iris-two": "#485cc5",
        "dark-blue-grey-two": "#192939",
        "style-22": "#7d6936",
        "pale-grey-three": "#f8f8f8",
        "very-light-grey": "#f3f4f6",
        "near-black": "#202020",
        "light-border": "#e5e7eb",
        "gray-f1": "#f1f1f1",
        "brand-red": "#e32026",
        "slate-65": "#5a6165",
        "gray-444": "#444444",
        "light-border-ec": "#e5e7ec",
        "near-navy": "#212a34",
      },
      fontSize: {
         "custom-xs": "12rem",
        "custom-sm": "14rem",
        "custom-lg": "18rem",
        "custom-2xl": "24rem",
        "custom-3xl": "28rem",
        "custom-4xl": "40rem",
      },
      borderRadius: {
        lg: "2rem"
      },
      gap: {
        "spacing-xxs": "4rem",
        "spacing-xs": "8rem",
        "spacing-s": "12rem",
        "spacing-m": "16rem",
        "spacing-l": "20rem",
        "spacing-xl": "24rem",
      },
      lineHeight: {
        none: "1",
        tight: "1.25",
        snug: "1.375",
        normal: "1.5",
        relaxed: "1.625",
        loose: "2",
      },
    },
  },
  corePlugins: {
    lineHeight: true,
  },
  plugins: [],
};
